baseURL: "https://econw18.classes.andrewheiss.com/"
languageCode: en-us
title: Economic Decision-Making for Managers
theme: ath-tufte-hugo
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Andrew Heiss
  thumbnail: /images/econ_meta.png
  instructor: 
    name: Dr. Andrew Heiss
    email: andrew_heiss@byu.edu
    url: "https://www.andrewheiss.com"
    twitter: andrewheiss
    github: andrewheiss
    office: 773 TNRB
  course:
    number: MPA 612
    semester: Winter 2018
    days: "MW; F (lab)"
    time: "9:30–10:45 AM (§1); 8:30–9:15 AM (§2); 12:30–1:45 PM (lab)"
    location: "170 TNRB (§1); 230 TNRB (§2); 230 TNRB (lab)"
    twitter: andrewheiss
    dates: "January 9–April 19, 2018"
    github: "andrewheiss/econw18.classes.andrewheiss.com"
    copyrightYear: "2017–2018"
    contactDetails: >-
      Office hours: Mondays from 10:30–11:30. [Sign up for other times here.](https://calendly.com/andrewheiss/meeting/)<br><br>E-mail is the best way to get in contact with me—I will respond to all course-related e-mails within 24 hours (*really*).
  university: 
    name: Brigham Young University
    url: "https://www.byu.edu"
  school:
    name: Romney Institute of Public Management
    url: "https://marriottschool.byu.edu/mpa/"
  description: "Understand and use economic reasoning to evaluate public policy and managerial decisions"
  primaryColor: "#5E81AC"
  secondaryColor: "#BF616A"
  credits: >-
    supply/demand curve icon by Andrew Heiss. [nord color scheme](https://github.com/arcticicestudio/nord) from [Arctic Ice Studio](http://arcticicestudio.com/).
  logo:
    url: /images/econ_hires.png
    alt: Economic decision-making for managers
  meta:
    twitterSite: "@andrewheiss"
    twitterCreator: "@andrewheiss"
    fbAuthor: "https://www.facebook.com/andrewheiss"
