---
title: "Firms and labor II"
date: "2018-02-07"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Required

***Important***: The PDF of "The Proper Scope of Government" is posted on Learning Suite.

- <i class="fa fa-book" aria-hidden="true"></i> 6.6–6.11 in *The Economy* [@core-econ]
- <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Oliver Hart and Andrei Shleifer and Robert W. Vishny, "The Proper Scope of Government: Theory and an Application to Prisons" [@HartShleiferVishny:1997]
    - ***Note***: This is really dense and the middle is full of equations. You can skip those. Read the introduction, discussion, and conclusion and make sure you understand the gist of the article.
- <i class="fa fa-external-link" aria-hidden="true"></i> Sam Dolnick, ["Air-Conditioners That Run When Nobody's Home,"](http://www.nytimes.com/2010/08/16/nyregion/16chill.html) New York Times, August 15, 2010
- <i class="fa fa-external-link" aria-hidden="true"></i> Ceci Connolly, ["U.S. worker's case reveals how drug cartels get help from this side of border,"](http://www.washingtonpost.com/wp-dyn/content/article/2010/09/11/AR2010091105087.html) Washington Post, September 12, 2010
- <i class="fa fa-external-link" aria-hidden="true"></i> Jeff Gottlieb and Ruben Vives, ["Is a city manager worth $800,000?,"](http://www.latimes.com/local/la-me-bell-salary-20100715-story.html) Los Angeles Times, July 15, 2010
- <i class="fa fa-external-link" aria-hidden="true"></i> Rob Ferguson, ["Ontario’s winter roads 'less safe' since privatization: auditor,"](https://www.thestar.com/news/canada/2015/04/29/ontarios-winter-roads-are-less-safe-since-privatization-auditor.html) The Star, April 29, 2015
