---
title: "When governments go wrong"
date: "2018-03-19"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
stuff-to-add: >-
  Durham freeway cutting through black neighborhoods
---

# Required

- <i class="fa fa-twitter" aria-hidden="true"></i> [Noah Smith on why we should worry about race, culture, and politics when thinking about economics](https://twitter.com/noahpinion/status/946446862898282496)
- <i class="fa fa-youtube" aria-hidden="true"></i> Adam Ruins Everything, ["The Disturbing History of the Suburbs"](https://www.youtube.com/watch?v=ETR9qrVS17g), October 4, 2017^[Yes, a CollegeHumor video. Seriously.]
- <i class="fa fa-external-link" aria-hidden="true"></i> Emma Roller's interview with Mehrsa Baradaran, ["How the U.S. Government Locked Black Americans Out of Attaining the American Dream,"](https://splinternews.com/how-the-u-s-government-locked-black-americans-out-of-a-1819221197), *Splinter*, October 11, 2017^[[Mehrsa is LDS](https://en.wikipedia.org/wiki/Mehrsa_Baradaran), btw.]
- <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Hamilton, et al., ["Umbrellas Don't Make it Rain: Why Studying and Working Hard Isn't Enough for Black Americans"](http://econ.hunter.cuny.edu/wp-content/uploads/2016/03/seminar2016-darity2.pdf) [@HamiltonDarityPrice:2015]
- <i class="fa fa-podcast" aria-hidden="true"></i> This American Life, ["The Problem We All Live With, Part One,"](https://www.thisamericanlife.org/562/the-problem-we-all-live-with-part-one) episode 562, July 31, 2015
- <i class="fa fa-podcast" aria-hidden="true"></i> This American Life, ["The Problem We All Live With, Part Two,"](https://www.thisamericanlife.org/563/the-problem-we-all-live-with-part-two) episode 563, August 7, 2015


# Not required, but highly recommended

- <i class="fa fa-external-link" aria-hidden="true"></i> Destin Jenkins, ["Who Segregated America?,"](http://www.publicbooks.org/who-segregated-america/) *Public Books*, December 21, 2017

