---
title: "Problem set 6"
date: "2018-03-23"
due_date: "2018-03-23"
due_time: "11:59 PM"
editor_options: 
  chunk_output_type: console
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

**Submit this as a PDF on Learning Suite.** *Show your work when possible.* You can use whatever you want to make your drawings, including Adobe Illustrator, Excel, PowerPoint, Microsoft Paint, [Desmos](https://www.desmos.com/), or scanned pen and paper.

**Cite your sources and show your work.**

# 1

To what degree is radio broadcasting a public good? To what degree is a highway a public good? Under what conditions might these two goods be purely private or purely public? **Answer in ≈30 words.**


# 2

In what sense is K–12 education a public good? How should your answer to this question affect the nature of government involvement in education? **Answer in ≈30 words.**


# 3

When the state of Virginia imposed stricter regulations on air pollution in 2003, it also authorized an auction of pollution permits, allowing some plants to emit larger amounts of CO~2~ than would otherwise be allowed, and some to emit less. Economic theory predicts that this action led to a socially efficient allocation of pollution. Describe how this outcome could occur. **Answer in ≈50 words.**


# 4

Consider **the society you live in,** or **another society** with which you are familiar.

1. To make this society fairer, would you want greater equality of income, happiness, or freedom? Why? Would there be a trade-off between these aspects? (**≈30 words**)
2. Are there other things that should be more equal to achieve greater fairness in this society? (**≈30 words**)
3. How fair is this society, according to the procedural judgements of fairness described in chapter 5 of CORE? (**≈30 words**)
4. How is Pareto efficiency different from fairness? (**≈30 words**)


# 5

Elinor Ostrom argues that commons problems are not public goods, but that institutions that govern the commons are. **Explain what she means in ≈50 words.**^[You need to [read her chapters from class 20](/reading/20-reading/) for this.]


# 6

How might Putnam's concept of social capital help explain why certain communities are better than others in solving collective action problems such as those posed by common pool resources? **Answer in ≈50 words.**


# 7

One solution to public goods problems involves estimating the demand for the public good, finding the socially optimal quantity, and taxing people at a per-unit level equal to their marginal benefit of the good. 

- Explain why this would, in theory, lead to the socially optimal level of the public good being provided. **Answer in ≈25 words.**
- What are some impediments to carrying out this tax strategy? **Answer in ≈25 words.**


# 8

In close congressional votes, many members of Congress choose to remain undecided until the last moment. Why might they do this? What lesson does this teach about a shortcoming of Coasian bargaining in fixing externalities? **Answer in ≈40 words.**


# 9

Suppose that the negative externalities associated with hog farming (including water pollution and airborne odors) are $5 per hog given current techniques.

1. Explain why "too many" hogs will be produced (**≈20 words**). In your answer use terms like "private cost" and "social cost." **Draw a diagram** of the hog market that illustrates your answer.
2. One proposal for solving this problem is to impose a tax of \$5. Explain the effect of such a tax and illustrate it on your diagram (**≈20 words**).  
3. What are the shortcomings of this solution? (**≈20 words**)
4. What alternative policies might be worth considering? (**≈30 words**)


# 10

If at least 29 students in the class complete this question, the entire class will get **10 extra credit points**.^[For real.] If fewer than 29 students do this, nobody will get extra credit.

Get a pencil and a sheet of paper. Write the following sentence, 20 times, by hand:

> I am willingly contributing to the production of this public good, even though I know that I will benefit even if I don't participate.

Take a picture of this and upload it with the rest of your assignment. It must be your own handwriting. If you work on this problem set in a group, each person must upload a picture of their own sheet of paper. 


# 11

In "The Problem of Social Cost" Coase claims that clear assignment of property rights can solve externality problems.   

1. Why does Coase argue that from a social perspective it should not matter whether the polluter pays for pollution or whether those affected by pollution pay the polluter not to pollute? **Answer in ≈30 words.**
2. Under what conditions does the Coase Theorem hold? When might we expect it not provide useful guidance for policy design? Why? **Answer in ≈30 words.**


# 12

Suppose the demand for newly legalized Coca Cola products at BYU is

$$
Q = 10,000 - 10,000P
$$

where Q is the number of cans of soft drink purchased per day and P is the price per can. The market supply curve is horizontal at \$0.75 per can.^[*Hint*: Remember that in supply/demand graphs, Q is on the x-axis and P is on the y-axis. You might need to do some algebra.] Given existing habits and disposal and recyling technology, it has been estimated that the average soft drink can ends up costing 10 cents in the form of unsightly litter and pick-up costs. 

1. Explain how the concept of market failure applies to this example (**≈20 words**). Illustrate your explanation with a graph showing the extent of this failure.^[*Hint*: think about social vs. private marginal costs] Be as precise as you can be in describing the extent of the failure.
2. Can society's loss from this market failure be quantified (**≈10 words**)? If so, calculate it as precisely as possible and indicate it in your illustration.
3. How could taxation be used to overcome this market failure? (**≈25 words**)
4. What are the shortcomings of this solution? (**≈25 words**)
5. What alternative policies might be worth considering? (**≈30 words**)


# 13

What do you think about the following (hypothetical) exchanges? You may assume in each case that the people involved are sane, rational adults who have thought about the alternatives and consequences of what they are doing. 

In each case, decide (1) whether you approve, (2) whether you think the transaction should be prohibited, and (3) what institutional or normative reasons support your decision. Discuss each in **≈30 words**.

1. Space Marketing Inc. announces plans to launch giant billboards made from Mylar sheets into low orbit. Companies would pay more than \$1 million dollars to display advertisements. Logos, about the size of the moon, will be visible to millions of people on Earth.
2. You are waiting in line to buy tickets for a movie that is almost sold out. Someone from the back of the line approaches the person in front of you and offers her $25 to let him in front of her.
3. A politically apathetic person, who never votes, agrees to vote in an election for the candidate who pays him the highest amount.
4. A well-informed and sane adult, with an adequate income, decides that he would like to sell himself to become the slave of another person. He finds a buyer willing to pay his asking price. The aspiring slave will give the price paid by the buyer to his children to further their education. 
